[package]
name = "fireworks"
authors = ["Arc-blroth <45273859+Arc-blroth@users.noreply.github.com>"]
license = "GPL-3.0-or-later"
version = "2.0.23"
edition = "2021"
private = true

[dependencies]
macroquad = { version = "0.3.25", default-features = false }
